compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  gateway-fm:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
